kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 6443 # API server inside the node
        hostPort: 6443 # pick a fixed, free host port
        listenAddress: "127.0.0.1"
        protocol: TCP
  - role: worker
  - role: worker
  - role: worker
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
