{
 "title": "carrier",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Broker HTTP Duration Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate({\"http_server_duration_milliseconds_bucket\", exported_job=\"broker\"}[$__rate_interval])))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate({\"http_server_duration_milliseconds_bucket\", exported_job=\"broker\"}[$__rate_interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate({\"http_server_duration_milliseconds_bucket\", exported_job=\"broker\"}[$__rate_interval])))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Broker HTTP RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate({\"http_server_duration_milliseconds_count\", exported_job=\"broker\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "External Carrier API Latency [P95]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (exported_job, le) (\r\n    rate(http_server_duration_milliseconds_bucket{\r\n      exported_job=~\"carrier-external-(dhl|fedex|ups)\"\r\n    }[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "External Carrier API Latency [P95]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.5,\r\n  sum by (exported_job, le) (\r\n    rate(http_server_duration_milliseconds_bucket{\r\n      exported_job=~\"carrier-external-(dhl|fedex|ups)\"\r\n    }[$__rate_interval])\r\n  )\r\n)",
     "legendFormat": "{{exported_job}}"
    }
   ]
  },
  {
   "title": "Total Shipments",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(shipment_counter_total{exported_job=\"broker\", status=\"received\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Carrier Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (carrierCode) (\r\n  increase(shipment_carrier_counter_total[$__rate_interval])\r\n)",
     "legendFormat": "{{carrierCode}}"
    }
   ]
  },
  {
   "title": "Service Graph",
   "type": "nodeGraph",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "filters": [
      { "id": "4e128009", "operator": "=", "scope": "span" }
     ],
     "limit": 20,
     "metricsQueryType": "range",
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Shipment Country Distribution",
   "type": "geomap",
   "gridPos": { "h": 26, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum by (destinationCountry) (\r\n  increase(shipment_country_counter_total[$__rate_interval])\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_group=\"carrier\"} | detected_level = `error`"
    }
   ]
  },
  {
   "title": "Warning Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_group=\"carrier\"} | detected_level = `warn`"
    }
   ]
  }
 ]
}