apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: carrier-wms
spec:
  commonName: 'wms.rimraf.de'
  dnsNames:
    - 'wms.rimraf.de'
  issuerRef:
    name: rimraf-cloudflare
    kind: ClusterIssuer
  secretName: carrier-wms-cert
