apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carrier-wms
spec:
  rules:
    - host: wms.rimraf.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-wms
                port:
                  number: 3100
  tls:
    - secretName: carrier-wms-cert
      hosts:
        - wms.rimraf.de
