apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: openfeature-flag-access
  namespace: default
rules:
  - apiGroups: ['core.openfeature.dev']
    resources: ['featureflags']
    verbs: ['get', 'list', 'watch']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openfeature-flag-access-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: Role
  name: openfeature-flag-access
  apiGroup: rbac.authorization.k8s.io
