apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-broker
  labels:
    app.kubernetes.io/component: broker
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: broker
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wms
  labels:
    app.kubernetes.io/component: wms
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3100
      targetPort: 3100
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: wms
---
#external carrier
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-external-dhl
  labels:
    app.kubernetes.io/component: external-dhl
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: external-dhl