apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-broker
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: broker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
    type: ClusterIP
    ports:
        - name: http
        port: 3000
        targetPort: 3000
        protocol: TCP
    selector:
        app.kubernetes.io/name: {{ include "helm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: broker
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}-wms
  labels:
    {{- include "helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: wms
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
    type: ClusterIP
    ports:
        - name: http
        port: 3100
        targetPort: 3100
        protocol: TCP
    selector:
        app.kubernetes.io/name: {{ include "helm.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: wms
