FROM node:alpine AS builder
WORKDIR /app
COPY . .
RUN npm install -g pnpm
RUN pnpm install
RUN pnpm run -r build:pkg
RUN pnpm deploy --legacy --filter carrier-internal deploy
RUN cd deploy
RUN pnpm run build

FROM node:alpine AS runtime
WORKDIR /app
COPY --from=builder /app/deploy/dist .
COPY --from=builder /app/deploy/package.json .
COPY --from=builder /app/deploy/node_modules ./node_modules
ENTRYPOINT [ "node", "index.js" ]