apiVersion: v2
name: carrier
description: A Helm chart for Kubernetes
version: 0.0.1
appVersion: '0.0.1'
dependencies:
  - name: redis
    version: 20.11.3
    repository: https://charts.bitnami.com/bitnami
  - name: open-feature-operator
    version: v0.8.5
    repository: https://open-feature.github.io/open-feature-operator/
