broker:
  enabled: true
  replicas: 1
  image:
    repository: 'ghcr.io/biclighter81/carrier-broker'
    tag: 'latest'
  resources:
    limits:
      cpu: '100m'
      memory: '128Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
wms:
  enabled: true
  replicas: 1
  image:
    repository: 'ghcr.io/biclighter81/carrier-wms'
    tag: 'latest'
  resources:
    limits:
      cpu: '100m'
      memory: '128Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
carriers:
  resources:
    limits:
      cpu: '500m'
      memory: '512Mi'
    requests:
      cpu: '250m'
      memory: '256Mi'
  internal:
    replicas: 1
    image:
      repository: ghcr.io/biclighter81/carrier-internal
      tag: latest
  external:
    dhl:
      replicas: 1
      image:
        repository: ghcr.io/biclighter81/carrier-external-dhl
        tag: latest

imagePullSecret: 'biclighter81-ghcr'
redis:
  enabled: true
  master:
    persistence:
      size: 2Gi
  architecture: standalone
  auth:
    enabled: false

open-feature-operator:
  otelCollectorUri: 'http://otel-opentelemetry-collector:4318'
