broker:
  replicas: 3
  image:
    repository: "localhost:5001/broker"
    tag: "latest"
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "1000m"
      memory: "1Gi"
wms:
  replicas: 1
  image:
    repository: "localhost:5001/wms"
    tag: "latest"
  resources:
    limits:
      cpu: "1000m"
      memory: "1Gi"
    requests:
      cpu: "1000m"
      memory: "1Gi"
carriers:
  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "250m"
      memory: "256Mi"
  internal:
    replicas: 1
    image:
      repository: localhost:5001/carrier
      tag: latest
  external:
    replicas: 1
    image:
      repository: localhost:5001/carrier-mock
      tag: latest
collectorUrl: "http://open-telemetry-opentelemetry-collector:4318"
imagePullSecret:
redis:
  enabled: true
  master:
    persistence:
      size: 2Gi
  architecture: standalone
  auth:
    enabled: false
