broker:
  enabled: true
  replicas: 1
  image:
    repository: 'ghcr.io/biclighter81/carrier-broker'
    tag: 'latest'
  resources:
    limits:
      cpu: '100m'
      memory: '128Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
wms:
  enabled: true
  replicas: 1
  image:
    repository: 'ghcr.io/biclighter81/carrier-wms'
    tag: 'latest'
  resources:
    limits:
      cpu: '100m'
      memory: '128Mi'
    requests:
      cpu: '100m'
      memory: '128Mi'
imagePullSecret: 'biclighter81-ghcr'
redis:
  enabled: true
  master:
    persistence:
      size: 2Gi
  architecture: standalone
  auth:
    enabled: false
