name: carrier-external-dhl
run-name: Build Job for carrier-external-dhl-${{github.event.client_payload.version}} on branch ${{github.event.client_payload.branch}}
on:
  repository_dispatch:
    types:
      - 'build-carrier-external-dhl'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/biclighter81/carrier-external-dhl
          tags: |
            ${{github.event.client_payload.version}}
            ${{github.event.client_payload.branch}}.next
            type=raw,value=latest,enable=${{ github.event.client_payload.branch == 'main' || github.event.client_payload.branch == 'master'}}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          ref: ${{ github.event.client_payload.branch }}
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
      - uses: pnpm/action-setup@v3
        with:
          version: 9.0.0
      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run -r build:pkg
          pnpm deploy --filter carrier-external-dhl deploy
          cd deploy
          pnpm run build
      - name: Build + Push
        uses: docker/build-push-action@v5
        with:
          tags: ${{ steps.meta.outputs.tags }}
          annotations: ${{ steps.meta.outputs.annotations }}
          context: ./deploy
          file: ./deploy/Dockerfile
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
